namespace SpriteKind {
    export const Boba = SpriteKind.create()
    export const Boba2 = SpriteKind.create()
}
sprites.onDestroyed(SpriteKind.Boba, function (sprite) {
    Boba1 = sprites.create(img`
        ....................
        ....................
        .........11.........
        .........11.........
        .........11.........
        .........11.........
        .....d9dddddddd.....
        .....dddddddddd.....
        ......66666666......
        ......dddddddd......
        .....dd9ddddddd.....
        .....d9dddddddd.....
        .....d9dddddddd.....
        .....dddddddddd.....
        .....dddddddddd.....
        .....dededdddde.....
        .....edededede6.....
        ......96666666......
        ....................
        ....................
        `, SpriteKind.Food)
    Boba1.x = randint(90, 90)
    Boba1.y = randint(90, 90)
})
sprites.onDestroyed(SpriteKind.Boba2, function (sprite) {
    Boba2 = sprites.create(img`
        ....................
        ....................
        .........11.........
        .........11.........
        .........11.........
        .........11.........
        .....d9dddddddd.....
        .....dddddddddd.....
        ......66666666......
        ......dddddddd......
        .....dd9ddddddd.....
        .....d9dddddddd.....
        .....d9dddddddd.....
        .....dddddddddd.....
        .....dddddddddd.....
        .....dededdddde.....
        .....edededede6.....
        ......96666666......
        ....................
        ....................
        `, SpriteKind.Food)
    Boba2.x = randint(90, 90)
    Boba2.y = randint(90, 90)
})
info.onLifeZero(function () {
    game.gameOver(false)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeScoreBy(1)
})
sprites.onDestroyed(SpriteKind.Enemy, function (sprite) {
    mySprite2 = sprites.create(img`
        . . . . . . . . . . . . . . 
        . . . . . f f f f . . . . . 
        . . . f f 5 5 5 5 f f . . . 
        . . f 5 5 5 5 5 5 5 5 f . . 
        . f 5 5 5 5 5 5 5 5 5 5 f . 
        c b 5 5 5 d b b d 5 5 5 b c 
        f 5 5 5 b d d d d b 5 5 5 f 
        f 5 5 c c d d d d c c 5 5 f 
        f b b f b f d d f b f b b f 
        f b b e 1 f d d f 1 e b b f 
        c f b d d d d d d d f b f c 
        . c d d d d 9 9 9 6 c e c . 
        . c d d d d 9 9 9 9 c d e . 
        . . c e e b b b 3 b b c e . 
        . . c c 3 b 3 b 3 3 c c . . 
        . . . . c c c b b c . . . . 
        `, SpriteKind.Enemy)
    mySprite2.follow(mySprite, 35)
    tiles.placeOnRandomTile(mySprite2, sprites.builtin.forestTiles0)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.setLife(3)
    info.changeLifeBy(-1)
})
let Boba2: Sprite = null
let Boba1: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
mySprite = sprites.create(assets.image`Adela`, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite, 100, 100)
mySprite2 = sprites.create(img`
    . . . . . . . . . . . . . . 
    . . . . . f f f f . . . . . 
    . . . f f 5 5 5 5 f f . . . 
    . . f 5 5 5 5 5 5 5 5 f . . 
    . f b 5 5 5 5 5 5 5 5 5 f . 
    c 5 5 5 5 d b b d 5 5 5 b c 
    f 5 5 5 b d d d d b 5 5 5 f 
    f 5 5 c c d d d d c c 5 5 f 
    f 5 5 f b f d d f b f b b f 
    f 5 5 e 1 f d d f 1 e b b f 
    c f 5 f d d d d d d d b f c 
    . c e c 6 9 9 9 d d d d c . 
    . e d c 9 9 9 9 d d d 4 c . 
    . e c b b 3 b b b e e c . . 
    . . c c 3 3 b 3 b 3 c c . . 
    . . . . c b b c c c . . . . 
    `, SpriteKind.Enemy)
mySprite2.follow(mySprite, 35)
tiles.placeOnTile(mySprite2, tiles.getTileLocation(2, 3))
Boba1 = sprites.create(img`
    ....................
    ....................
    .........11.........
    .........11.........
    .........11.........
    .........11.........
    .....d9dddddddd.....
    .....dddddddddd.....
    ......66666666......
    ......dddddddd......
    .....dd9ddddddd.....
    .....d9dddddddd.....
    .....d9dddddddd.....
    .....dddddddddd.....
    .....dddddddddd.....
    .....dededdddde.....
    .....edededede6.....
    ......96666666......
    ....................
    ....................
    `, SpriteKind.Food)
Boba1.y = randint(0, 90)
Boba2 = sprites.create(img`
    ....................
    ....................
    .........11.........
    .........11.........
    .........11.........
    .........11.........
    .....d9dddddddd.....
    .....dddddddddd.....
    ......66666666......
    ......dddddddd......
    .....dd9ddddddd.....
    .....d9dddddddd.....
    .....d9dddddddd.....
    .....dddddddddd.....
    .....dddddddddd.....
    .....dededdddde.....
    .....edededede6.....
    ......96666666......
    ....................
    ....................
    `, SpriteKind.Food)
Boba2.x = randint(90, 90)
let Boba3 = sprites.create(img`
    ....................
    ....................
    .........11.........
    .........11.........
    .........11.........
    .........11.........
    .....d9dddddddd.....
    .....dddddddddd.....
    ......66666666......
    ......dddddddd......
    .....dd9ddddddd.....
    .....d9dddddddd.....
    .....d9dddddddd.....
    .....dddddddddd.....
    .....dddddddddd.....
    .....dededdddde.....
    .....edededede6.....
    ......96666666......
    ....................
    ....................
    `, SpriteKind.Food)
Boba3.x = randint(90, 90)
music.play(music.stringPlayable("E B C5 A B G A F ", 120), music.PlaybackMode.UntilDone)
Boba3.x = randint(90, 90)
mySprite2.y = 0
let projectile = 0
